apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-collector-deployment
spec:
  selector:
    matchLabels:
      app: ip-collector
  template:
    metadata:
      labels:
        app: ip-collector
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: script-volume
          configMap:
            name: script-config
      containers:
        - name: ip-extractor
          image: amazonlinux
          command: ["/bin/bash", "-c", "cp /scripts/create_file.sh /tmp/create_file.sh && chmod +x /tmp/create_file.sh && /tmp/create_file.sh"]
          volumeMounts:
            - mountPath: /shared-data
              name: shared-data
            - mountPath: /scripts
              name: script-volume
        - name: s3-uploader
          image: amazon/aws-cli
          command: ["/bin/bash", "-c", "cp /scripts/upload_s3.sh /tmp/upload_s3.sh && chmod +x /tmp/upload_s3.sh && /tmp/upload_s3.sh"]
          volumeMounts:
            - mountPath: /shared-data
              name: shared-data
