name: Deploy Infra

on:
  push:
    branches:
      - develop
      - feature/*
    paths:
      - 'iac/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'iac/**'
  workflow_dispatch:

jobs:
  feature-branch:
    if: contains(github.ref, 'feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Initialize Terraform
        run: |
          cd iac
          terraform init

      - name: Validate Terraform
        run: |
          cd iac
          terraform validate

      - name: Terraform Plan
        run: |
          cd iac
          terraform plan

  deploy:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: feature-branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Initialize Terraform
        run: |
          cd iac
          terraform init

      - name: Apply Terraform
        run: |
          cd iac
          terraform apply -auto-approve